<?php
$teams = [
    "ABFC",
    "AC Ajaccio",
    "AC Milan",
    "ACA",
    "ACFC",
    "AEK Athènes",
    "AEK Larnaca",
    "ALB",
    "ALG",
    "ALM",
    "AM",
    "AND",
    "ANG",
    "ARG",
    "ARM",
    "AS Roma",
    "ASC",
    "ASF",
    "ASM",
    "ASM II",
    "ASMB",
    "ASNL",
    "ASPTT Dijon",
    "ASSE",
    "ASSP",
    "ASV",
    "AUS",
    "AUT",
    "AZ Alkmaar",
    "AZE",
    "Abel Braga",
    "Accrington Stanley",
    "Agde",
    "Aigues-Mortes",
    "Aire-sur-la-Lys",
    "Ajaccio",
    "Ajaccio II",
    "Ajax",
    "Ajax Amsterdam",
    "Al Jazira Club",
    "Al-Qadisiyah",
    "Alain Perrin",
    "Alavés",
    "Albert Emon",
    "Albi",
    "Alès",
    "Alès-en-Cévennes",
    "Amiens",
    "Anderlecht",
    "André Villas-Boas",
    "Andrézieux-Bouthéon",
    "Angers",
    "Angoulême Soyaux Charente",
    "Annecy",
    "Antwerp",
    "Anvers",
    "Aris Limassol",
    "Arles",
    "Arles-Avignon",
    "Arsenal",
    "Aston Villa",
    "Atalanta",
    "Atalanta Bergame",
    "Athletic",
    "Athletic Bilbao",
    "Athletic Club",
    "Athlético Marseille",
    "Atletico Madrid",
    "Atlético",
    "Aubagne",
    "Augsbourg",
    "Australie",
    "Auxerre",
    "Avoine-Chinon-Cinais",
    "Avranches",
    "BATE",
    "BDI",
    "BEL",
    "BEN",
    "BF",
    "BFA",
    "BIH",
    "BK Häcken",
    "BLR",
    "BLZ",
    "BOL",
    "BOT",
    "BPFC",
    "BRA",
    "BUL",
    "Backa Topola",
    "Bahreïn",
    "Balagne",
    "Balma",
    "Bastia",
    "Bastia-Borgo",
    "Bayer Leverkusen",
    "Bayern",
    "Bayern Munich",
    "Beaucaire",
    "Beauvais",
    "Benevento",
    "Benfica",
    "Bergerac",
    "Bernard Casoni",
    "Besiktas",
    "Betis",
    "Betis Séville",
    "Beşiktaş",
    "Bodo Glimt",
    "Bodø-Glimt",
    "Bologne",
    "Borac",
    "Bordeaux",
    "Borussia Dortmund",
    "Boulogne",
    "Bourg-Peronnas",
    "Bourg-en-Bresse",
    "Bourgoin-Jallieu",
    "Bournemouth",
    "Braga",
    "Bratislava",
    "Brest",
    "Brighton",
    "Brondby",
    "Bruges",
    "Brøndby IF",
    "Burnley",
    "Bâle",
    "Béziers",
    "CAN",
    "CAP",
    "CAT",
    "CF63",
    "CGO",
    "CHA",
    "CHI",
    "CIV",
    "CMR",
    "CNFC",
    "COD",
    "COL",
    "COM",
    "CPV",
    "CRC",
    "CRO",
    "CSKA Moscou",
    "CSKA Moskva",
    "CTA",
    "CUB",
    "CUW",
    "CYP",
    "CZE",
    "Cadix",
    "Caen",
    "Cagnes-Le-Cros",
    "Calonne-Ricouart",
    "Canet",
    "Canet-en-Roussillon",
    "Cannes",
    "Cannet-Rocheville",
    "Carnoux",
    "Castelnau-Le Crès",
    "Cavigal Nice",
    "Celje",
    "Celta Vigo",
    "Celtic",
    "Celtic Glasgow",
    "Cercle Brugge",
    "Chakhtar Donetsk",
    "Challans",
    "Chamalières",
    "Chambly",
    "Chambéry",
    "Chapeau 1",
    "Chapeau 2",
    "Chapeau 3",
    "Chapeau 4",
    "Charleroi",
    "Charleville-Mézières",
    "Chartres",
    "Chatou",
    "Chauvigny",
    "Chelsea",
    "Christophe Bouchet",
    "Christophe Galtier",
    "Châteaubriant",
    "Châteauroux",
    "Clermont",
    "Clermont Foot",
    "Club Bruges",
    "Club Brugge",
    "Club Franciscain",
    "Cologne",
    "Colomiers",
    "Concarneau",
    "Copenhague",
    "Corte",
    "Corée du Sud",
    "Croatie",
    "Crystal Palace",
    "Créteil",
    "D.C. United",
    "DEN",
    "DFCO",
    "DOM",
    "DOMTAC",
    "Didier Deschamps",
    "Dijon",
    "Dinamo",
    "Dinamo Zagreb",
    "Dinan-Léhon",
    "Dives-Cabourg",
    "Djurgarden",
    "Djurgårdens",
    "Dnipro-1",
    "Dortmund",
    "Dunkerque",
    "Dynamo",
    "Dynamo Kiev",
    "Dynamo Kyiv",
    "EA Ligue 1 Games",
    "EAG",
    "ECA",
    "ECU",
    "EFCFSR",
    "EGY",
    "ENG",
    "EQG",
    "ESALM91",
    "ESCL",
    "ESMGO",
    "ESP",
    "ESSG",
    "EST",
    "ESTAC",
    "ESV",
    "ETH",
    "EUGA Ardziv",
    "Elche",
    "Elfsborg",
    "Empoli",
    "Endoume",
    "Entente UGA Ardziv",
    "Espanyol Barcelone",
    "Etoile Rouge Belgrade",
    "Everton",
    "Excelsior Maassluis",
    "FBBP01",
    "FC Barcelone",
    "FC Bâle",
    "FC DAC",
    "FC Lyon",
    "FC Pinzgau",
    "FC Porto",
    "FC Séville",
    "FC2A",
    "FCBB",
    "FCC85",
    "FCCO",
    "FCD",
    "FCF91",
    "FCGB",
    "FCL",
    "FCLSD",
    "FCMB",
    "FCN",
    "FCR",
    "FCS",
    "FCSB",
    "FCSM",
    "FCV78",
    "FCVB",
    "FIN",
    "FRA",
    "FRO",
    "Fabrègues",
    "Feignies-Aulnoye",
    "Feignies-Aulnoye-Aymeries",
    "Fenerbahce",
    "Fenerbahçe",
    "Ferencvaros",
    "Ferencváros",
    "Ferencvárosi",
    "Feyenoord",
    "Fiorentina",
    "Flamengo",
    "Fleury",
    "Fleury 91",
    "Fluminense",
    "Fos-sur-Mer",
    "Francfort",
    "Francfort II",
    "Franck Passi",
    "Frank McCourt",
    "Fribourg",
    "Fréjus Saint-Raphaël",
    "GAB",
    "GAM",
    "GBR",
    "GEO",
    "GER",
    "GF38",
    "GFA 74",
    "GFC Ajaccio",
    "GFCA",
    "GHA",
    "GIB",
    "GLP",
    "GOAL FC",
    "GRE",
    "GSI",
    "GUA",
    "GUI",
    "GUY",
    "Galatasaray",
    "Galicia",
    "Gardanne",
    "Genas",
    "Genk",
    "Gennaro Gattuso",
    "Genoa",
    "Gent",
    "Getafe",
    "Ghisonaccia",
    "Giovanni Ciccolunghi",
    "Glasgow Rangers",
    "Granada",
    "Grasse",
    "Grenade",
    "Grenoble",
    "Guichen",
    "Guingamp",
    "Guéret",
    "Gérone",
    "HAC",
    "HAI",
    "HFC",
    "HON",
    "HUN",
    "Hajduk Split",
    "Hauts Lyonnais",
    "Hellas Verone",
    "Hertha Berlin",
    "Hoffenheim",
    "Huesca",
    "Hyères",
    "ICC",
    "IDN",
    "IRL",
    "IRN",
    "ISL",
    "ISR",
    "ITA",
    "Igor Tudor",
    "Inter",
    "Inter Milan",
    "Irak",
    "Iran",
    "Istanbul",
    "Istanbul Basaksehir",
    "Istres",
    "JAM",
    "JPN",
    "JSSP",
    "Jacques Abardonado",
    "Jacques-Henri Eyraud",
    "Jagiellonia",
    "Japon",
    "Javier Clemente",
    "Jean Fernandez",
    "Jean-Claude Dassier",
    "Jean-Louis Gasset",
    "Jorge Sampaoli",
    "Josip Skoblar",
    "José Anigo",
    "Jumeaux de M'zouazia",
    "Jura Sud Foot",
    "Juventus",
    "Juventus Turin",
    "KAS Eupen",
    "KAZ",
    "KGZ",
    "KOR",
    "KOS",
    "KSA",
    "Konyaspor",
    "Krasnodar",
    "KÍ",
    "LASK",
    "LBC",
    "LBR",
    "LBY",
    "LDAS",
    "LES",
    "LMFC",
    "LOSC",
    "LPF43",
    "LTU",
    "LUX",
    "LVA",
    "La Gantoise",
    "La Roche-sur-Yon",
    "Larnaca",
    "Las Palmas",
    "Laval",
    "Lazio",
    "Lazio Rome",
    "Le Cannet-Rocheville",
    "Le Havre",
    "Le Mans",
    "Le Poiré-sur-Vie",
    "Le Puy",
    "Le Rove",
    "Lech",
    "Lech Poznan",
    "Leeds",
    "Legia Warszawa",
    "Leicester",
    "Leicester City",
    "Leipzig",
    "Lens",
    "Les Herbiers",
    "Levante",
    "Leverkusen",
    "Libourne",
    "Lille",
    "Limassol",
    "Liverpool",
    "Lokomotiv Moscou",
    "Lokomotiv Moskva",
    "Lokomotiv Plovdiv",
    "Loon-Plage",
    "Lorient",
    "Louhans-Cuiseaux",
    "Lucciana",
    "Ludogorets",
    "Lugano",
    "Lusitano FCV",
    "Luynes",
    "Lyon",
    "Lyon II",
    "Lyon-La Duchère",
    "Lège-Cap-Ferret",
    "MAD",
    "MAR",
    "MDA",
    "MDA Foot",
    "MEX",
    "MGFC",
    "MHSC",
    "MKD",
    "MLI",
    "MLT",
    "MNE",
    "MOS",
    "MOZ",
    "MSR",
    "MTN",
    "MWI",
    "MYA",
    "MYF 03",
    "Maccabi Haïfa",
    "Maccabi Tel Aviv",
    "Malaga",
    "Malmö",
    "Manchester City",
    "Manchester United",
    "Mantes-la-Ville",
    "Marcelino",
    "Marcelo Bielsa",
    "Margarita Louis-Dreyfus",
    "Marignane Gignac",
    "Marignane Gignac II",
    "Marignane Gignac-Côte Bleue",
    "Marmande",
    "Marseille",
    "Martigues",
    "Mayence",
    "Metz",
    "Middlesbrough",
    "Midtjylland",
    "Milan",
    "Milan AC",
    "Molde",
    "Monaco",
    "Monchengladbach",
    "Montagnarde",
    "Montauban",
    "Montpellier",
    "Montpellier II",
    "Mtsapéré",
    "Mulhouse",
    "Mâcon",
    "Mérignac",
    "Míchel",
    "Mönchengladbach",
    "NAM",
    "NCA",
    "NED",
    "NGA",
    "NIG",
    "NIR",
    "NLGFC",
    "NO",
    "NOR",
    "NZL",
    "Nancy",
    "Nanterre",
    "Nantes",
    "Naples",
    "Napoli",
    "Nasser Larguet",
    "Newcastle",
    "Nice",
    "Nice II",
    "Nimes",
    "Niort",
    "Norwich",
    "Nottingham Forest",
    "Nîmes",
    "Nîmes II",
    "OGCN",
    "OGS",
    "OL",
    "OM",
    "OM (F)",
    "OM 1981-1982",
    "OM 1982-1983",
    "OM 1983-1984",
    "OM 1984-1985",
    "OM 1985-1986",
    "OM 1986-1987",
    "OM 1987-1988",
    "OM 1988-1989",
    "OM 1989-1990",
    "OM 1990-1991",
    "OM 1991-1992",
    "OM 1992-1993",
    "OM 1993-1994",
    "OM 1994-1995",
    "OM 1996-1997",
    "OM 1997-1998",
    "OM 1998-1999",
    "OM 1999-2000",
    "OM 2000-2001",
    "OM 2001-2002",
    "OM 2002-2003",
    "OM 2003-2004",
    "OM 2004-2005",
    "OM 2005-2006",
    "OM 2006-2007",
    "OM 2007-2008",
    "OM 2008-2009",
    "OM 2009-2010",
    "OM 2010-2011",
    "OM 2011-2012",
    "OM 2012-2013",
    "OM 2013-2014",
    "OM 2014-2015",
    "OM 2015-2016",
    "OM 2016-2017",
    "OM 2017-2018",
    "OM 2018-2019",
    "OM 2019-2020",
    "OM 2020-2021",
    "OM 2021-2022",
    "OM 2022-2023",
    "OM 2023-2024",
    "OM 2024-2025",
    "OM 2025-2026",
    "OM II",
    "OM U17",
    "OM U19",
    "OS",
    "OSQ",
    "Olympiacos",
    "Olympiakos",
    "Omonia",
    "Orléans",
    "Osasuna",
    "Ostende",
    "Ouest Tourangeau",
    "PAN",
    "PAOK",
    "PAR",
    "PER",
    "PFC",
    "POL",
    "POR",
    "PSG",
    "PSV",
    "PSV Eindhoven",
    "Pablo Longoria",
    "Pafos",
    "Panathinaikos",
    "Pape Diouf",
    "Paris FC",
    "Partizan",
    "Partizan Belgrade",
    "Pau",
    "Pau FC",
    "Paços de Ferreira",
    "Perpignan",
    "Philippe Troussier",
    "Plzen",
    "Plzeň",
    "Porto",
    "Prix-Lès-Mézières",
    "Pyunik",
    "QAT",
    "Qarabag",
    "Qarabağ",
    "Qatar",
    "Quevilly",
    "Quevilly-Rouen",
    "RAF",
    "RB Leipzig",
    "RC de France",
    "RCL",
    "RCSA",
    "RED",
    "RFS",
    "RKC Waalwijk",
    "ROU",
    "RSA",
    "RUS",
    "RWA",
    "Racing Genk",
    "Raków",
    "Randers",
    "Rangers",
    "Rangers FC",
    "Rapid",
    "Rapid Vienne",
    "Rayo Vallecano",
    "Real Madrid",
    "Real Sociedad",
    "Red Star",
    "Reims",
    "Reims Saint-Anne",
    "Rennes",
    "Rennes II",
    "Riviera",
    "Robert Louis-Dreyfus",
    "Roberto De Zerbi",
    "Rodez",
    "Rolland Courbis",
    "Roma",
    "Romorantin",
    "Rosenborg",
    "Rouen",
    "Rousset",
    "Rudi Garcia",
    "Ruh Lviv",
    "République populaire de Chine",
    "SAS",
    "SB",
    "SB29",
    "SC Air Bel",
    "SCB",
    "SCO",
    "SDN",
    "SDR",
    "SEN",
    "SLV",
    "SMC",
    "SMR",
    "SP",
    "SPAL",
    "SPSH",
    "SR",
    "SRB",
    "SRFC",
    "SSD",
    "SSEP",
    "SUI",
    "SUR",
    "SV Heimstetten",
    "SVK",
    "SVN",
    "SWE",
    "SWZ",
    "Sablé",
    "Saint-Brice",
    "Saint-Brieuc",
    "Saint-Clément-Montferrier",
    "Saint-Etienne",
    "Saint-Louis Neuweg",
    "Saint-Omer",
    "Saint-Priest",
    "Sainte-Lucie-de-Porto-Vecchio",
    "Salernitana",
    "Salzbourg",
    "Salzburg",
    "Sannois-Saint-Gratien",
    "Sarre-Union",
    "Sassuolo",
    "Saumur",
    "Schalke 04",
    "Schiltigheim",
    "Sedan",
    "Servette FC",
    "Sete",
    "Seyssinet-Pariset",
    "Shakhtar",
    "Shakhtar Donetsk",
    "Shanghai",
    "Sheffield United",
    "Sheriff",
    "Sheriff Tiraspol",
    "Shkupi",
    "Sinnamary",
    "Sivasspor",
    "Slavia",
    "Slavia Prague",
    "Slovan Bratislava",
    "Sochaux",
    "Southampton",
    "Soyaux",
    "Soyaux-Charente",
    "Sparta Prague",
    "Spartak Moscou",
    "Spezia",
    "Sporting",
    "Sporting - CP",
    "Sporting CP",
    "Sporting II",
    "Stade Briochin",
    "Stade Poitevin",
    "Stade Portelois",
    "Stoke City",
    "Strasbourg",
    "Sturm Graz",
    "Stuttgart",
    "Sunderland",
    "Sète",
    "Séville FC",
    "TAH",
    "TAN",
    "TFC",
    "TJK",
    "TOG",
    "TUN",
    "TUR",
    "Thaon",
    "Thaon-les-Vosges",
    "Thionville-Lusitanos",
    "Tigres",
    "Torcy",
    "Torino",
    "Tottenham",
    "Tottenham Hotspur",
    "Tottenham II",
    "Toulon",
    "Toulouse",
    "Tours",
    "Trabzonspor",
    "Troyes",
    "Trélissac",
    "Twente",
    "UCL P1",
    "UCL P2",
    "UCL P3",
    "UCL P4",
    "UGA",
    "UJS Toulouse",
    "UKR",
    "URU",
    "USA",
    "USG",
    "USO",
    "USR",
    "USSO",
    "UZB",
    "Udinese",
    "Union Berlin",
    "Union SG",
    "Union Saint-Gilloise",
    "Uruguay",
    "VAFC",
    "VEN",
    "VHF",
    "Valence",
    "Valence CF",
    "Valencia",
    "Valenciennes",
    "Valladolid",
    "Versailles",
    "VfB Stuttgart",
    "Vierzon",
    "Villarreal",
    "Villefranche",
    "Villefranche Saint-Jean Beaulieu",
    "Villefranche-Beaujolais",
    "Villenave-d'Ornon",
    "Vincent Labrune",
    "Vissel Kobe",
    "Vitesse",
    "Vitória Guimarães",
    "Viêt Nam",
    "Vénissieux",
    "WAL",
    "Wasquehal",
    "Watford",
    "West Ham",
    "Wolfsberg",
    "Wolfsbourg",
    "Wolfsburg",
    "Wolverhampton",
    "Young Boys",
    "Yves Marchand",
    "ZAM",
    "ZIM",
    "Zenit",
    "Zoran Vujović",
    "Zurich",
    "Zürich",
    "Élie Baup",
    "Émirats arabes unis",
    "Épernay",
    "Épinal",
    "Éric Gerets",
    "Étoile Rouge de Belgrade",
    "Étoile rouge",
    "Évian",
    "Žilina"
];